### ISSUE TITLE
Error: Could not find newline in intermediate buffer; check input convert2bed

### ISSUE THREAD

**Issue by vrutantshah** [bedops/bedops#148] opened 2015-08-13 23:03 UTC
Hi Alex,

I have 9 samples, I am using sam files to convert into bed files using convert2bed script. 6 out of 9 samples works fine, only for 3 samples i see this error : Error: Could not find newline in intermediate buffer; check input convert2bed

Please let me know what may the issue be, and how cna i resolve it.

Vrutant

**Comment by alexpreynolds** [comment] 2015-08-13 23:34
Do you have SAM files with very long reads?

**Comment by sjneph** [comment] 2015-08-14 03:14
Another thought - make sure these files were not created on Windows with
both CR+LF as a newline.  If so, run them through dos2unix before using the
conversion tool.

**Comment by vrutantshah** [comment] 2015-08-14 04:40
no, the reads are in fact short. i had other replicate sample, which worked
fine only three of them are giving this error. I am trying to convert them
into bam and then will try one more time converting into bed files.

thank you for getting back.

Vrutant

On Thu, Aug 13, 2015 at 6:34 PM, Alex Reynolds <notifications@github.com>
wrote:

> Do you have SAM files with very long reads?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bedops/bedops/issues/148#issuecomment-130883693>.
>



-- 
*Vrutant Shah*
Ph.D. Candidate
University of Houston

**Comment by alexpreynolds** [comment] 2015-08-14 06:17
If you can share the relevant SAM files, I can attempt conversion to try to determine the cause of problems. Let me know if you would like to pursue this option.

**Comment by alexpreynolds** [comment] 2015-08-18 21:40
I cannot reproduce the error, so I'm going to close this. If you would like to troubleshoot further, please feel free to update this thread or contact me directly.

**Closed by alexpreynolds** 2015-08-18 21:40 UTC
