### ISSUE TITLE
feature-request - gtf2bed: on failure, output help to stderr

### ISSUE THREAD

**Issue by russHyde** [bedops/bedops#225] opened 2019-06-24 10:26 UTC
Hi.
I was trying to convert a human/ensembl .gtf file (ftp://ftp.ensembl.org/pub/release-84/gtf/homo_sapiens/Homo_sapiens.GRCh38.84.gtf.gz) to .bed using gtf2bed using the following command line:

```
cat Homo_sapiens.GRCh38.84.gtf.gz | gunzip - > Homo_sapiens.GRCh38.84.gtf

gtf2bed -i gtf --do-not-sort < Homo_sapiens.GRCh38.84.gtf > sorted.bed
```

The command failed with error code 1. That isn't a problem, I'll work out how to filter/reformat the input gtf.

But the command printed the gtf2bed help page to the file `sorted.bed`.

Would it be possible to output error messaging to `stderr` rather than `stdout` (but still print user-requested --help to stdout)?

**Comment by alexpreynolds** [comment] 2019-06-24 12:34
https://www.biostars.org/p/206342/

**Comment by russHyde** [comment] 2019-06-24 12:46
Thanks, but I've already fixed the file munging problem.

The issue was about `gtf2bed` passing what-would typically be an error message to stdout

**Comment by alexpreynolds** [comment] 2019-11-20 19:23
Thanks for posting this issue.

Under a Darwin build of v2.4.38 (equivalent to v2.4.37, at the time this message is written):

```
$ wget -qO- "ftp://ftp.ensembl.org/pub/release-84/gtf/homo_sapiens/Homo_sapiens.GRCh38.84.gtf.gz" | gunzip - > /tmp/Homo_sapiens.GRCh38.84.gtf
$ ./bin/convert2bed --input=gtf --do-not-sort < /tmp/Homo_sapiens.GRCh38.84.gtf > /tmp/unsorted.bed
Error: Potentially missing gene or transcript ID from GTF attributes (malformed GTF at line [1]?)
$ echo $?
96
$ ll /tmp/unsorted.bed 
-rw-r--r--  1 areynolds  wheel  0 Nov 20 11:12 /tmp/unsorted.bed
```

Under Linux:

```
$ wget -qO- "ftp://ftp.ensembl.org/pub/release-84/gtf/homo_sapiens/Homo_sapiens.GRCh38.84.gtf.gz" | gunzip - > /tmp/Homo_sapiens.GRCh38.84.gtf
$ ./bin/convert2bed --input=gtf --do-not-sort < /tmp/Homo_sapiens.GRCh38.84.gtf > /tmp/unsorted.bed
Error: Potentially missing gene or transcript ID from GTF attributes (malformed GTF at line [1]?)
$ echo $?
61
$ ls -al /tmp/unsorted.bed 
-rw-r--r-- 1 areynolds stamlab 0 Nov 20 11:16 /tmp/unsorted.bed
```

On both platforms, I get a non-zero status code (in a `bash` environment) and zero-byte result files (no messages are written to stdout, which would have gone to these results, creating non-zero-byte files).

Because I can't reproduce this with functionality in the current version (the development branch v2.4.38 has an equivalent `convert2bed`, at this time, to v2.4.37), I'll close this ticket for now. 

If you have examples of the stdout from this or a similar command, please post them here and I'll reopen this and investigate again.

**Closed by alexpreynolds** 2019-11-20 19:23 UTC
