### ISSUE TITLE
convert2bed-megarow fails with "Could not find newline" when given very large SAM files

### ISSUE THREAD

**Issue by SchwarzEM** [bedops/bedops#208] opened 2018-04-10 17:37 UTC
Having triumphantly overcome the 'segmentation fault' bug of convert2bed-megarow (which has just been corrected in v2.4.33), I proceeded to feed seven chromosome-alignment SAM files (all generated by minimap2 from single-chromosome alignments of two different versions of the reference C. elegans genome assembly) into convert2bed-megarow for conversion to BED files.

Here is the first command that I ran on a small SAM alignment of mitochondrial chromosomes -- which worked flawlessly:

    cat vc2010_M.minimap2.n2_MtDNA.sam | convert2bed-megarow --input=sam --output=bed - 1>vc2010_M.minimap2.n2_MtDNA.bed 2>vc2010_M.minimap2.n2_MtDNA.err ;

The error file (vc2010_M.minimap2.n2_MtDNA.err) was zero-byte and the BED alignment file (vc2010_M.minimap2.n2_MtDNA.bed) was exactly identical to that produced by other versions of convert2bed.  So far, so good.

But then I tried submitting six other large SAM alignments of nuclear chromosomes to convert2bed-megarow, as follows:

    cat vc2010_I.minimap2.n2_I.sam | convert2bed-megarow --input=sam --output=bed - 1>vc2010_I.minimap2.n2_I.bed 2>vc2010_I.minimap2.n2_I.err ;

    cat vc2010_II.minimap2.n2_II.sam | convert2bed-megarow --input=sam --output=bed - 1>vc2010_II.minimap2.n2_II.bed 2>vc2010_II.minimap2.n2_II.err ;

    cat vc2010_III.minimap2.n2_III.sam | convert2bed-megarow --input=sam --output=bed - 1>vc2010_III.minimap2.n2_III.bed 2>vc2010_III.minimap2.n2_III.err ;

    cat vc2010_IV.minimap2.n2_IV.sam | convert2bed-megarow --input=sam --output=bed - 1>vc2010_IV.minimap2.n2_IV.bed 2>vc2010_IV.minimap2.n2_IV.err ;

    cat vc2010_V.minimap2.n2_V.sam | convert2bed-megarow --input=sam --output=bed - 1>vc2010_V.minimap2.n2_V.bed 2>vc2010_V.minimap2.n2_V..err ;

    cat vc2010_X.minimap2.n2_X.sam | convert2bed-megarow --input=sam --output=bed - 1>vc2010_X.minimap2.n2_X.bed 2>vc2010_X.minimap2.n2_X.err ;

However, all six of these line commands failed!  In each case, I had equivalent error messages.  Specifically, they were:

vc2010_I.minimap2.n2_I.err:

    Error: Could not find newline in intermediate buffer; check input [52147 | 4947853 | 5000000]
    /bin/cat: write error: Broken pipe

vc2010_II.minimap2.n2_II.err:

    Error: Could not find newline in intermediate buffer; check input [19382 | 4980618 | 5000000]
    /bin/cat: write error: Broken pipe

vc2010_III.minimap2.n2_III.err:

    Error: Could not find newline in intermediate buffer; check input [84921 | 4915079 | 5000000]
    /bin/cat: write error: Broken pipe

vc2010_IV.minimap2.n2_IV.err:

    Error: Could not find newline in intermediate buffer; check input [19382 | 4980618 | 5000000]
    /bin/cat: write error: Broken pipe

vc2010_V.minimap2.n2_V..err:

    Error: Could not find newline in intermediate buffer; check input [150451 | 4849549 | 5000000]
    /bin/cat: write error: Broken pipe

vc2010_X.minimap2.n2_X.err:

    Error: Could not find newline in intermediate buffer; check input [52147 | 4947853 | 5000000]
    /bin/cat: write error: Broken pipe

Is there something I should be specifically doing differently when I present very large SAM files to convert2bed-megarow?  Or are these errors due to a fixable bug?

It may be helpful if others working on this problem can download the SAM files that I used for this work.  Fortunately, I've placed all of the SAM files (both the large six nuclear chromosome-based files, and the small mitochondrial chromosome-based file) on the Web with an MD5 checksum file, so that they can be downloaded and tested on other people's computers.  Here they are:

http://woldlab.caltech.edu/~schwarz/VC2010_assemblies/miniasm_alignments

Thank you for any information or advice that you have!

**Comment by alexpreynolds** [comment] 2018-04-10 18:38
Each stage of conversion is a "thread" that has a buffer associated with it, which temporarily stores data processed by that stage. This buffer is 5 MB in size. 

If a newline cannot be found inside that buffer, then an error is returned. SAM files (or any input) with records longer than 5 MB will not be able to get through. This is the case with at least one of your test inputs, e.g.:

```
$ awk '{print length($0);}' /tmp/vc2010_I.minimap2.n2_I.sam | sort -nr | head -3
15335425
1101308
904281
```

As you can see, the longest newline-delimited record in this SAM file is ~15 MB in size.

The buffer size is perhaps not a bug so much as a design choice. A larger buffer size has a cost of increased memory overhead and runtime. 

What I'll probably do for v2.4.34 is make the buffer size available as a runtime option you can pass to `convert2bed`. The default buffer size will be bumped up, probably, but it can be increased manually, if an error is encountered.

In the meantime, if you want to get up and running sooner and you are comfortable with compiling the toolkit, you can make a custom build by first editing `<bedops_root>/applications/bed/conversion/src/convert2bed.h` and modifying the value of `C2B_THREAD_IO_BUFFER_SIZE` to something larger, e.g. 20M or more. Then compile, as usual (http://bedops.readthedocs.io/en/latest/content/installation.html#installation-via-source-code).

**Comment by SchwarzEM** [comment] 2018-04-10 18:53
That all makes sense, and your very fast response is a great help!

I'll try compiling from source with an edited `C2B_THREAD_IO_BUFFER_SIZE` variable, and see what happens.  Previous source compilations of bedops have been very easy, so this is hardly a draconian stopgap.

**Comment by SchwarzEM** [comment] 2018-04-10 21:12
So, I've compiled from source with an edited `C2B_THREAD_IO_BUFFER_SIZE` variable in `<bedops_root>/applications/bed/conversion/src/convert2bed.h`.  Here's the change I made:

    85c85
    < #define C2B_THREAD_IO_BUFFER_SIZE 5000000
    ---
    > #define C2B_THREAD_IO_BUFFER_SIZE 100000000

After compiling this modified bedops source tree, and running this command:

    cat vc2010_I.minimap2.n2_I.sam | convert2bed-megarow --input=sam --output=bed - 1>vc2010_I.minimap2.n2_I.bed 2>vc2010_I.minimap2.n2_I.err ;

I got the following error message:

    BED row length exceeds capacity at line 1 in -.
    Check that you have unix newlines (cat -A) or increase TOKENS_MAX_LENGTH in BEDOPS.Constants.hpp and recompile BEDOPS.
    Error: Stage [Sorted BED to stdout] failed -- exit status [256 | 1]

I went back to the source code, ran `make clean`, and did more editing (this time on `<bedops_root>/interfaces/general-headers/suite/BEDOPS.Constants.hpp`).  Here are my (admittedly naive) changes:

    127c127
    <   constexpr LineLengthType  TOKENS_MAX_LENGTH        = INT_TOKENS_MAX_LENGTH;
    ---
    >   constexpr LineLengthType  TOKENS_MAX_LENGTH        = (100*INT_TOKENS_MAX_LENGTH);
    152c152
    < #define TOKENS_MAX_LENGTH INT_TOKENS_MAX_LENGTH
    ---
    > #define TOKENS_MAX_LENGTH (100*INT_TOKENS_MAX_LENGTH)

However, when rerunning the above command, I still got an error message:

    BED row length exceeds capacity at line 1 in -.
    Check that you have unix newlines (cat -A) or increase TOKENS_MAX_LENGTH in BEDOPS.Constants.hpp and recompile BEDOPS.

So, I'm left with the suspicion that `<bedops_root>/interfaces/general-headers/suite/BEDOPS.Constants.hpp` needs to be revised, but with no good idea about how to do it...

**Comment by sjneph** [comment] 2018-04-10 21:51
When you compile, use: `make megarow && make install_megarow`

This will pass in the megarow constants through the compiler:
`-DREST_EXPONENT=22 -DID_EXPONENT=18 -DCHROM_EXPONENT=8`

Those can be modified near the top of the makefile if needed.  The values that they expand to are 2^value-1 such as 2^22-1 for REST_EXPONENT.

**Comment by alexpreynolds** [comment] 2018-04-10 21:51
One thing you can do immediately is add the `--do-not-sort` option to `convert2bed`, which side-steps the use of `sort-bed` to do sorting. Because `sort-bed` does not get used to sort, that error should be eliminated. The output is in the order of records from the original SAM file.

    $ convert2bed --do-not-sort --input=sam < long-lined.sam > long-lined.unsorted.bed

If you want `sort-bed` sort order, then you do need to compile a custom version of BEDOPS (and `sort-bed`) with the edited `TOKENS_MAX_LENGTH` variable. The issue may be where those custom binaries are located.

If `--do-not-sort` is *not* specified, then `convert2bed` will process converted data with `sort-bed`. To do this, it looks for the first copy of `sort-bed` it can find in your environment's `PATH`. 

This can mean that `convert2bed` may not be using your custom-built `sort-bed`, but rather an older stock version that does not have your line-length customization.

For example, If you have a stock copy of `sort-bed` in `/usr/local/bin` and a custom copy of `sort-bed` compiled and installed in `<bedops_root>/bin`, then what you might do is first edit the `PATH` variable:

    $ PATH=<bedops_root>/bin:$PATH

You might use `echo $PATH` to double-check things. Then run `convert2bed`:

    $ convert2bed --input=sam < long-lined.sam > long-lined.sorted.bed

Given the matter of sorting, I'm going to think a little more about this buffer size issue before making changes, perhaps tying buffer size explicitly to the suite-wide constants and not allow runtime configuration. People can compile a custom version if the megarow build is not sufficient.

**Comment by alexpreynolds** [comment] 2018-04-10 22:01
Note: I made some edits to my comment to make it more explicit what compiled version of `convert2bed` is being run in the command-line examples. These edits will not show up in the email that Github sends to people tracking this discussion thread, so it may make sense to reload the issue's URL (https://github.com/bedops/bedops/issues/208).

**Comment by SchwarzEM** [comment] 2018-04-10 22:24
I actually did prepend the newly compiled binaries into $PATH, so the newly compiled `sort-bed` binary was used alongside the newly compiled `convert2bed`:

        which sort-bed ;

    ~/src/bedops-2.4.33/bin/sort-bed

        which convert2bed ;

    ~/src/bedops-2.4.33/bin/convert2bed

Also: when I compiled the new binaries from source code, I ran `make all`.  I had naively assumed that this included all of the effects of running `make megarow`.   Is this not true?

**Comment by SchwarzEM** [comment] 2018-04-10 22:27
Also, I notice that in my second effort, I did not observe this part of the error message (which I had observed previously).

    error: Stage [Sorted BED to stdout] failed -- exit status [256 | 1]

So, is it possible that my efforts to edit `TOKENS_MAX_LENGTH` did succeed in enabling `sort-bed` to work?

**Comment by alexpreynolds** [comment] 2018-04-10 22:59
This indicates that the sort step failed, which makes sense as lines are being passed into `sort-bed` that are too long for it, as compiled. This may indicate that the conversion step of `convert2bed` is "working", but use of `--do-not-sort` would confirm that. I'll use your sample SAM input to reproduce this on my end.

**Comment by sjneph** [comment] 2018-04-10 23:02
When you run: `~/src/bedops-2.4.33/bin/sort-bed --version`
You should see this line:  version:  `2.4.33 (megarow)`
If it shows 'typical' in place of 'megarow', then that's likely the issue.

**Comment by SchwarzEM** [comment] 2018-04-11 02:42
I've managed to compile binaries for `convert2bed` that cleanly convert all of my chromosome-scale SAM alignments to BED!

Here's how:

    cd $HOME/TGZ ;
    wget https://github.com/bedops/bedops/archive/v2.4.33.tar.gz ;
    mv -i v2.4.33.tar.gz bedops-2.4.33.tar.gz ;

    cd $HOME/src ;
    zcat $HOME/TGZ/bedops-2.4.33.tar.gz | tar xf - ;

    cd $HOME/src/bedops-2.4.33/applications/bed/conversion/src ;
    cp -ip convert2bed.h orig_convert2bed.h_file ;

    # Increase C2B_THREAD_IO_BUFFER_SIZE to 100 MB
    nano convert2bed.h ;

    # Here's what changed:
    diff orig_convert2bed.h_file convert2bed.h ;

    85c85
    < #define C2B_THREAD_IO_BUFFER_SIZE 5000000
    ---
    > #define C2B_THREAD_IO_BUFFER_SIZE 100000000

    cd /mnt/home/emsch/src/bedops-2.4.33/interfaces/general-headers/suite ;

    cp -ip BEDOPS.Constants.hpp orig_BEDOPS.Constants.hpp_file ;

    # Increase TOKENS_MAX_LENGTH 100-fold (why think small?)
    nano BEDOPS.Constants.hpp ;

    # Here's what changed:
    diff orig_BEDOPS.Constants.hpp_file BEDOPS.Constants.hpp ;

    127c127
    <   constexpr LineLengthType  TOKENS_MAX_LENGTH        = INT_TOKENS_MAX_LENGTH;
    ---
    >   constexpr LineLengthType  TOKENS_MAX_LENGTH        = (100*INT_TOKENS_MAX_LENGTH);
    152c152
    < #define TOKENS_MAX_LENGTH INT_TOKENS_MAX_LENGTH
    ---
    > #define TOKENS_MAX_LENGTH (100*INT_TOKENS_MAX_LENGTH)

    cd $HOME/src/bedops-2.4.33 ;

    make megarow ;
    make install_megarow ;
    
    cd $WORK_DIR ;  

    PATH="$HOME/src/bedops-2.4.33/bin:$PATH" ;
    export PATH ;

    # Make all the SAMs:
    cat vc2010_I.minimap2.n2_I.sam     | convert2bed --input=sam --output=bed - 1>vc2010_I.minimap2.n2_I.bed 2>vc2010_I.minimap2.n2_I.err ;
    cat vc2010_II.minimap2.n2_II.sam   | convert2bed --input=sam --output=bed - 1>vc2010_II.minimap2.n2_II.bed 2>vc2010_II.minimap2.n2_II.err ;
    cat vc2010_III.minimap2.n2_III.sam | convert2bed --input=sam --output=bed - 1>vc2010_III.minimap2.n2_III.bed 2>vc2010_III.minimap2.n2_III.err ;
    cat vc2010_IV.minimap2.n2_IV.sam   | convert2bed --input=sam --output=bed - 1>vc2010_IV.minimap2.n2_IV.bed 2>vc2010_IV.minimap2.n2_IV.err ;
    cat vc2010_V.minimap2.n2_V.sam     | convert2bed --input=sam --output=bed - 1>vc2010_V.minimap2.n2_V.bed 2>vc2010_V.minimap2.n2_V..err ;
    cat vc2010_X.minimap2.n2_X.sam     | convert2bed --input=sam --output=bed - 1>vc2010_X.minimap2.n2_X.bed 2>vc2010_X.minimap2.n2_X.err ;
    cat vc2010_M.minimap2.n2_MtDNA.sam | convert2bed --input=sam --output=bed - 1>vc2010_M.minimap2.n2_MtDNA.bed 2>vc2010_M.minimap2.n2_MtDNA.err ;

    rm *.err ;   # all zero-byte!

So, that's it.

Some points:

1. Automatic sorting of the BED outputs worked fine.

2. I think that @sjneph had an important point about compiling *only* the megarow applications; doing that ensured that `sort_bed` was itself guaranteed to be a megarow application.  I suspect that other changes associated with megarow-only compilation (i.e., the automatic setting of constants `-DREST_EXPONENT=22 -DID_EXPONENT=18 -DCHROM_EXPONENT=8`).

3. Given the `make megarow; install_megarow` strategy, the combination of the code change suggested by @alexpreynolds and my own naive 100-fold increase of `TOKENS_MAX_LENGTH` worked.  Omitting either code change did not work.

**Comment by SchwarzEM** [comment] 2018-04-11 15:12
Thanks to @alexpreynolds and @sjneph for their fast and extensive help!

**Comment by alexpreynolds** [comment] 2018-04-11 18:53
Glad it all worked out! 

The next version of `convert2bed` will deal with this via the suite-wide constants, so that there is only one file to edit (and fewer constants to edit) in order to make custom versions that support longer line lengths.

I'll close this up for now, but please feel free to add comments if you run into any further problems.

**Closed by alexpreynolds** 2018-04-11 18:53 UTC
Labels: enhancement, feature request, question
